"use strict";

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "src");
const OUTPUT = path.join(ROOT, "watchapedia-exporter.user.js");
const pkg = JSON.parse(
  fs.readFileSync(path.join(ROOT, "package.json"), "utf8"),
);

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(full);
    return entry.name.endsWith(".js") ? [full] : [];
  });
}

function moduleId(file) {
  return path
    .relative(SRC, file)
    .replaceAll(path.sep, "/")
    .replace(/\.js$/, "");
}

const modules = walk(SRC)
  .sort()
  .map((file) => {
    const id = moduleId(file);
    const source = fs.readFileSync(file, "utf8").trimEnd();
    return `    ${JSON.stringify(id)}: function(module, exports, require) {\n${source
      .split("\n")
      .map((line) => `      ${line}`)
      .join("\n")}\n    }`;
  })
  .join(",\n");

const header = `// ==UserScript==\n// @name         WatchaPedia Ratings Exporter\n// @namespace    watchapedia-ratings-exporter\n// @version      ${pkg.version}\n// @description  왓챠피디아 영화·시리즈 평가를 CSV로 백업하고 기존 백업을 증분 갱신합니다.\n// @match        https://pedia.watcha.com/ko\n// @match        https://pedia.watcha.com/ko/*\n// @updateURL    https://raw.githubusercontent.com/pottq577/watchapedia-export/main/watchapedia-exporter.user.js\n// @downloadURL  https://raw.githubusercontent.com/pottq577/watchapedia-export/main/watchapedia-exporter.user.js\n// @license      PolyForm-Noncommercial-1.0.0\n// @run-at       document-idle\n// @grant        none\n// ==/UserScript==`;

const bundle = `${header}\n\n// Generated by scripts/build.js. Edit src/* and run npm run build.\n(() => {\n  "use strict";\n\n  const __modules = {\n${modules}\n  };\n  const __cache = Object.create(null);\n\n  function __resolve(from, request) {\n    if (!request.startsWith(".")) return request;\n    const parts = from.split("/").slice(0, -1);\n    for (const part of request.split("/")) {\n      if (!part || part === ".") continue;\n      if (part === "..") parts.pop();\n      else parts.push(part);\n    }\n    return parts.join("/");\n  }\n\n  function __require(id) {\n    if (__cache[id]) return __cache[id].exports;\n    const factory = __modules[id];\n    if (!factory) throw new Error(\`Unknown module: \${id}\`);\n    const module = { exports: {} };\n    __cache[id] = module;\n    factory(module, module.exports, (request) => __require(__resolve(id, request)));\n    return module.exports;\n  }\n\n  __require("main");\n})();\n`;

fs.writeFileSync(OUTPUT, bundle, "utf8");
console.log(`built ${path.basename(OUTPUT)} (${pkg.version})`);
